feat(github-ci): add GitHub Action to install dfx
dfinity/setup-dfx pull request #2
Opened 2023-08-20 20:28 UTC by mmicu

# Description

Add a GitHub Action that installs `dfx` in GitHub Action Workflow.

# How Has This Been Tested?

`act` can be used to test this new action, together with `.github/workflows/tests/dfx-action.yml`:

```
$ act -W .github/workflows/tests/dfx-action.yml
```

2023-08-24 23:11 UTC, ericswanson-dfinity commented on .github/workflows/tests/dfx-action.yml
> +      - '.github/workflows/tests/dfx-action.yml'
I notice this didn't run for this PR.  Does the file need to be in the workflows directory, like `.github/workflows/dfx-action.yml` ?

2023-08-29 19:33 UTC, mmicu commented on .github/workflows/tests/dfx-action.yml
> +      - '.github/workflows/tests/dfx-action.yml'
I moved the file, but I cannot see any run as well. Do we need any additional GitHub configuration?

2023-08-29 21:07 UTC, ericswanson-dfinity commented on action.yml
> +          DFX_VERSION=${{ inputs.dfx-version }} sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
```suggestion
          DFX_VERSION="${{ inputs.dfx-version }}" sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"
```

2023-08-29 21:20 UTC, ericswanson-dfinity requested changes

2023-08-29 21:20 UTC, ericswanson-dfinity commented on .github/workflows/dfx-action.yml
> +      - 'action.yml'
We should set this up as a required check.

There are two options for this:
- run on all PRs (remove these path qualifiers)
- add a second workflow with the same name that passes if this one doesn't run (paths-ignore)

For a single-focus repo like this one, I'm not sure it's worth it to try to limit when this workflow runs, so I'd recommend to remove the path qualifiers.

```suggestion
```

2023-08-29 21:20 UTC, ericswanson-dfinity commented on .github/workflows/dfx-action.yml
> +      - 'action.yml'
```suggestion
```

2023-08-29 22:04 UTC, ericswanson-dfinity approved these changes

2023-08-29 22:04 UTC, merged

2023-08-29 22:06 UTC, ericswanson-dfinity commented on .github/workflows/tests/dfx-action.yml
> +      - '.github/workflows/tests/dfx-action.yml'
Workflow ran and passed after merge.  Thanks @mmicu!